import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Test;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import pojo.UserPayload;
import pojo.UserResponse;

import java.time.Duration;
import java.time.format.ResolverStyle;


public class HybridE2ETest {

    @Test
    public void apiToUiHandoffTEst() throws Exception {
        Reporter.log("<b>--- PHASE 1: BACKEND API DATA CREATION ---</b>", true);

        // 1. Fetch API key
        String mySecretKey = utils.ConfigReader.getProperty("reqres.api.key");

        // 2. Create the exact Payload we want to inject into the UI later
        String expectedSearchName = "Hybrid Automation User";
        UserPayload newUserData = new UserPayload(expectedSearchName, "SDET");

        // 3. Fire the POST request
        Response response = RestAssured.given()
                .header("x-api-key", mySecretKey)
                .header("User-Agent", "PostmanRuntime/7.32.3")
                .header("Content-Type", "application/json")
                .body(newUserData)
                .post("https://reqres.in/api/users");

        // 4. Catch the Response (Deserialization)
        UserResponse createdUser = response.as(UserResponse.class);

        // THE ENTERPRISE SECRET: We capture the ID dynamically generated by the API!
        String generatedUserId = createdUser.getId();

        Reporter.log("Successfully created user via API! Generated ID: " + generatedUserId, true);
        Reporter.log("<b>--- PHASE 2: FRONTEND UI HANDOFF ---</b>", true);

        // ==============================================================
        // PHASE 2: UI (Selenium Webdriver)
        // ==============================================================

        // 5. Boot up Chrome (We will keep it visible so you can watch the magic)
        ChromeOptions options = new ChromeOptions();
        /*
        options.addArguments("--start-maximized"); // (You can actually delete --start-maximized, it doesn't do much in headless mode anyway)
        */
        options.addArguments("--headless"); // THE FIX: Tell Chrome to run invisibly for GitHub Actions!
        options.addArguments("--window-size=1920,1080"); // 🚨 THE FIX: Force a 1080p desktop viewport!
        WebDriver driver = new ChromeDriver(options);
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        try {
            // 6. Navigate to a safe, public UI to test our data injection
            // We use Wikipedia just as a safe playground to inject our text
            driver.get("https://en.wikipedia.org/wiki/Main_Page");
            Reporter.log("Navigated to UI portal.", true);

            // 7. Find the search box
            WebElement searchBox = wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("search")));

            // THE HANDOFF MAGIC: We type the exact data generated by our API into the frontend UI!
            String combinedDataToType = expectedSearchName + "(ID: " + generatedUserId + ")";
            searchBox.sendKeys(combinedDataToType);

            Reporter.log("Successfully injected API data into the UI search box: " + combinedDataToType, true);

           /*
            // Give you 3 seconds to visually watch it happen before it closes
            Thread.sleep(3000);
            */

            // 8. THE SPEED STRIKE: Assert instantly BEFORE Wikipedia's Javascrpt refreshes the DOM!

            //    THE CLOUD-READY ASSERTION: Always re-find elements that might refresh!

            WebElement freshSearchBox = driver.findElement(By.name("search"));

            String actualValueInBox = searchBox.getAttribute("value");
            Assert.assertTrue(actualValueInBox.contains(generatedUserId), "The API ID did not make it to the UI!");

            // Now that the test has officially passed, pause for 3 seconds so you can watch it!
            Thread.sleep(3000);

        } finally {
            // 9. Always clean up the browser
            driver.quit();
            Reporter.log("<b>--- HYBRID E2E TEST COMPLETE ---</b>", true);
        }
    }
}
