name: Enterprise Docker Automation Pipeline

# 1. THE TRIGGER
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker-execution:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Download Repository Code
        uses: actions/checkout@v4

      # 2. THE ENGINE: We no longer install Java/Chrome manually. Docker does it all!
      - name: 🐳 Build Docker Container
        run: docker build -t jpmc-automation-engine .

      # 3. THE IGNITION: Run the container, pass the secret, and build a tunnel for the reports
      - name: 🚀 Execute Framework Inside Docker
        # The '-v' command maps the container's target folder to the GitHub server
        # We also pass your specific REQRES_API_KEY directly into the container!
        run: docker run -v ${{ github.workspace }}/target:/usr/src/app/target jpmc-automation-engine mvn test -Dtest=TestRunner -Dreqres.api.key=${{ secrets.REQRES_API_KEY }}

      # 4. THE RESCUE: Grab the reports that escaped through the tunnel
      - name: 📁 Rescue the HTML Reports (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Full-Automation-Reports
          path: target/